#!/bin/bash
#
# Barney Desmond <barneydesmond@gmail.com>, 2015
#
# SCRIPT TO:
#   1. Take a file
#   2. Hash it (sha1)
#   3. Upload to crispyr, URL is printed on output
#   4. Could optionally put URL on clipboard
#
# REQUIRES xclip and s3cmd
#
# READS DESTINATION BUCKET NAME FROM ~/.crisprbucket
#


S3BASE="beta.anchortrove.com"
BUCKET=$(cat ~/.crisprbucket || echo crispr)

FILEPATH=$1
FILENAME=$(basename $FILEPATH)
if [[ ! -f "$FILEPATH" ]] ; then
	echo "$FILEPATH isn't a file, exiting."
	exit 2
fi

FILEHASH=$(sha1sum -b < "$FILEPATH" | cut -d' ' -f1)

CALLED_AS=$(basename $0)
case "$CALLED_AS" in
	crput)
		UPLOAD_NAME="$FILENAME"
		;;
	*)
		UPLOAD_NAME="$FILEHASH"
esac


s3cmd -c ~/s3cfg/work put -P "$FILEPATH" "s3://${BUCKET}/${UPLOAD_NAME}"
PUBLIC_URL="http://${BUCKET}.${S3BASE}/${UPLOAD_NAME}"

LZMAURL=$(lzmafy "$PUBLIC_URL")
if [ -z $LZMAURL ] ; then
	echo "Problem shortening URL: $PUBLIC_URL"
	exit 1
fi
echo $LZMAURL

# chuck it in the clipboard
echo -n "$LZMAURL" | xclip -selection clipboard

# tell the window manager too
notify-send -u low -t 500 "$LZMAURL"
